spring:
  application:
    name: rating-services
  config:
    import:
    - optional:configserver:http://localhost:8888
resilience4j:
  ratelimiter:
    instances:
      userHotelRatingLimiter:
        timeoutDuration: 5s
        limitRefreshPeriod: 1s 
        limitForPeriod: 10