spring:
  application:
    name: user-service
  config:
    import:
    - optional:configserver:http://localhost:8888
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
          include: health
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true 


resilience4j.circuitbreaker:
  instances:
    ratingHotelBreaker:
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 50s
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowSize: 10
      slidingWindowType: count-based