spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mahmoud-fouad/hotel-micro-configuration-center
          clone-on-start: true
server:
  port: 8888
